learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
app_name = 'myapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special', views.special, name='special')
]

myapp/urls.py
from django.urls import path, include
from . import views

app_name = 'myapp'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login', views.user_login, name='user_login'),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='myapp/profile_pic', blank=True)

    def __str__(self):
        return self.user.first_name

myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','first_name','last_name', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

myapp/views.py
from django.shortcuts import render
from myapp.forms import UserForm, UserProfileInfoForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
# Create your views here.
def index(request):
    return render(request, 'myapp/index.html')

def register(request):
    registered = False
    if(request.method == "POST"):
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else :
            print(user_form.errors, profile_form.errors)
    else:

        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'myapp/registration.html', {'user_form':user_form ,
                                                            'profile_form':profile_form,
                                                            'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if(user):
            if(user.is_active):
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print("Someone entered wrong password and failed")
            print("username:{}, password:{}".format(username, password))
            return HttpResponse("Invalid login details supplied")

    else:
        return render(request, 'myapp/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("Great, you are logged out")

templates/myapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="nav-item nav-link" href="{% url 'myapp:register' %}">Register</a></li>

          {% if user.is_authenticated %}
          <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a> </li>
          {% else %}
          <li> <a class="navbar-link" href="{% url 'myapp:user_login' %}">Login</a> </li>

          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

templates/myapp/index.html
<!DOCTYPE html>
{% extends "myapp/base.html" %}

{% block body_block %}

<div class="jumbotron">
  <h1>This is home page</h1>
</div>
{% endblock %}

templates/myapp/login.html
{% extends 'myapp/base.html' %}

{% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form  action="{% url 'myapp:user_login'%}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter Username">
      <label for="password">Password:</label>
      <input type="password" name="password">
      <input type="submit" value="login">
  </form>
</div>

{% endblock %}

templates/myapp/registration.html
{% extends 'myapp/base.html' %}

{% load static %}

{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registering </h1>
    {% else %}
      <h1>Register here </h1>
      <h3>Fill out form</h3>
    <form enctype="multipart/form_data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Submit">
    </form>
    {% endif %}
  </div>
{% endblock %}